server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 10.100.86.2
    port: 5672
    username: venus
    password: venus
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /venus
#    listener:
#      simple:
#        acknowledge-mode: manual
#      direct:
#        acknowledge-mode: manual